from django.conf import settings

LOGGING_TELEGRAM_ACTIONS = getattr(settings, "TELEGRAM_ACTION_LOG", True)
CASE_INSENSITIVE_USERNAME_LOOKUP = getattr(
	settings, "TELEGRAM_CASE_INSENSITIVE_USERNAME_LOOKUP", False
)
REQUIRE_USERNAME = getattr(settings, "TELEGRAM_REQUIRE_USERNAME", False)
ACTIVATE_INACTIVE_USERS = getattr(settings, "TELEGRAM_ACTIVATE_INACTIVE_USERS", False)
