from django.conf import settings

TELEGRAM_TOKEN = getattr(settings, "TELEGRAM_TOKEN", None)
ROOT_UTRLCONF = settings.TELEGRAM_ROOT_UTRLCONF
LOGGING_TELEGRAM_ACTIONS = getattr(settings, "TELEGRAM_ACTION_LOG", True)
CASE_INSENSITIVE_USERNAME_LOOKUP = getattr(
	settings, "TELEGRAM_CASE_INSENSITIVE_USERNAME_LOOKUP", False
)
REQUIRE_USERNAME = getattr(settings, "TELEGRAM_REQUIRE_USERNAME", False)
SEND_TRIGGER_BLOCK_SIZE = getattr(settings, "TELEGRAM_SEND_TRIGGER_BLOCK_SIZE", 500)
LOG_REQUESTS = getattr(settings, "TELEGRAM_LOG_REQUESTS", False)
